apiVersion: v1
kind: Service
metadata:
  name: library
  labels:
    name: library
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: library