apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: authentication-storage
  name: authentication-storage
spec:
  replicas: 1
  selector:
    name: authentication-storage
  template:
    metadata:
      labels:
        name: authentication-storage
    spec:
      containers:
      - image: jenca/jenca-authentication
        name: authentication-storage
        command: ["python","storage/storage.py"]
        env:
        - name: POSTGRES_HOST
          value: "env:XXX"
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DATABASE
          value: "jenca-authentication"
        ports:
        - containerPort: 5001
          name: http-server