apiVersion: v1
kind: Service
metadata:
  name: auth-storage
  labels:
    name: auth-storage
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: auth-storage