apiVersion: v1
kind: Service
metadata:
  name: authentication-storage
  labels:
    name: authentication-storage
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    name: authentication-storage