apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: projects
  name: projects
spec:
  replicas: 1
  selector:
    name: projects
  template:
    metadata:
      labels:
        name: projects
    spec:
      containers:
      - image: jenca/jenca-projects
        name: projects
        env:
        - name: LEVEL_HOST
          value: "env:PROJECTS_STORAGE_SERVICE_HOST"
        - name: AUTH_HOST
          value: "env:AUTHENTICATION_SERVICE_HOST"
        - name: RUNTIME_HOST
          value: "env:RUNTIME_SERVICE_HOST"
        ports:
        - containerPort: 80
          name: http-server