apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: projects-storage
  name: projects-storage-controller
spec:
  replicas: 1
  selector:
    name: projects-storage
  template:
    metadata:
      labels:
        name: projects-storage
    spec:
      containers:
      - image: jenca/jenca-level-storage
        name: projects-storage
        ports:
        - containerPort: 80
          name: http-server