apiVersion: v1
kind: Service
metadata:
  name: projects-storage
  labels:
    name: projects-storage
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: projects-storage