apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: authorization-db
  name: authorization-db
spec:
  replicas: 1
  selector:
    name: authorization-db
  template:
    metadata:
      labels:
        name: authorization-db
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
          name: postgres-server