apiVersion: v1
kind: Service
metadata:
  name: authorization-db
  labels:
    name: authorization-db
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: authorization-db