apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  type: LoadBalancer
  ports:
    - port: 2368
      targetPort: 2368
      protocol: TCP
  selector:
    app: redmine
