apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: library
  name: library-controller
spec:
  replicas: 1
  selector:
    name: library
  template:
    metadata:
      labels:
        name: library
    spec:
      containers:
      - image: jenca/jenca-library
        name: library
        ports:
        - containerPort: 80
          name: http-server