apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: gui
  name: gui
spec:
  replicas: 1
  selector:
    name: gui
  template:
    metadata:
      labels:
        name: gui
    spec:
      containers:
      - image: jenca/jenca-gui
        name: gui
        ports:
        - containerPort: 8080
          name: http-server