apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    name: router
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: router