apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: router
  name: router-controller
spec:
  replicas: 1
  selector:
    name: router
  template:
    metadata:
      labels:
        name: router
    spec:
      containers:
      - image: gcr.io/jenca-cloud/jenca-router:latest
        name: router
        ports:
        - containerPort: 80
          name: http-server