apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: authentication
  name: authentication
spec:
  replicas: 1
  selector:
    name: authentication
  template:
    metadata:
      labels:
        name: authentication
    spec:
      containers:
      - image: jenca/jenca-authentication
        name: authentication
        command: ["python","authentication/authentication.py"]
        env:
        - name: SECRET_KEY
          value: "secret"
        - name: STORAGE_HOST
          value: "env:XXX"
        ports:
        - containerPort: 5000
          name: http-server