apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    name: authentication
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: authentication