apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: authorization
  name: authorization
spec:
  replicas: 1
  selector:
    name: authorization
  template:
    metadata:
      labels:
        name: authorization
    spec:
      containers:
      - image: jenca/jenca-authorization
        name: authorization
        env:
        - name: POSTGRES_HOST
          value: "env:AUTHORIZATION_DB_SERVICE_HOST"
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DATABASE
          value: "jenca-authorization"
        ports:
        - containerPort: 80
          name: http-server