apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: authorization
  name: authorization-controller
spec:
  replicas: 1
  selector:
    name: authorization
  template:
    metadata:
      labels:
        name: authorization
    spec:
      containers:
      - image: jenca/jenca-authorization
        name: authorization
        ports:
        - containerPort: 80
          name: http-server