apiVersion: v1
kind: Service
metadata:
  name: authorization
  labels:
    name: authorization
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: authorization